parameters:
  - name: AzDOEnvironmentName
    type: string
  - name: TFStateResourceGroupName
    type: string
  - name: TFStateStorageAccountName
    type: string
  - name: TFStateContainerName
    type: string
  - name: TFStateBlobName
    type: string
  - name: TerraformWorkspace
    type: string
  - name: TerraformArtifactConfigRelativePath
    type: string
  - name: TerraformArtifact
    type: string
  - name: VariablesTemplateRelativePath
    type: string
  - name: TerraformVariableMappings
    type: object
  - name: TerraformOutputVariables
    type: object
  - name: TerraformContainer
    value: string

jobs:
  - deployment: planInfrastructure
    displayName: "Plan Infrastructure"
    container: ${{if parameters.TerraformContainer}}
    workspace:
      clean: all
    variables:
      - template: ${{variables['System.DefaultWorkingDirectory']}}${{ parameters.VariablesTemplateRelativePath }}@self
    environment: "${{ parameters.AzDOEnvironmentName }}"
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: UKHOTemplates
              persistCredentials: true
              path: devops-pipelinetemplates

            - download: current
              artifact: "${{ parameters.TerraformArtifact }}"
              retryCountOnTaskFailure: '2'
              displayName: 'Download terraform artifact'

            - task: PowerShell@2
              name: plan
              displayName: "terraform plan"
              inputs:
                targetType: filePath
                filePath: "$(Pipeline.Workspace)/devops-pipelinetemplates/gated-infrastructure-deploy/terraform-plan.ps1"
                arguments: >
                  -TFStateResourceGroupName ${{ parameters.TFStateResourceGroupName }}
                  -TFStateStorageAccountName ${{ parameters.TFStateStorageAccountName }}
                  -TFStateContainerName ${{ parameters.TFStateContainerName }}
                  -TFStateBlobName ${{ parameters.TFStateBlobName }}
                  -TerraformFilesDirectory "$(Pipeline.Workspace)/${{ parameters.TerraformArtifact }}${{ parameters.TerraformArtifactConfigRelativePath }}"
                  -Workspace ${{ lower(parameters.TerraformWorkspace) }}
              env:
                ${{ each TerraformVariableMappings in parameters.TerraformVariableMappings }}:
                  ${{ TerraformVariableMappings.Key }}: ${{ TerraformVariableMappings.Value }}

  - job: manualVerification
    dependsOn: planInfrastructure
    pool: server
    condition: eq(dependencies.planInfrastructure.outputs['planInfrastructure.plan.needsVerification'], 'true')
    displayName: "Service Manual Verification"
    steps:
      - task: Delay@1
        displayName: "👇🔁 Refresh browser if button to verify Terraform Plan does not appear in the task below"

      - task: ManualValidation@0
        displayName: "Accept or Reject Plan?"
        timeoutInMinutes: 60

  - deployment: deployInfrastructure
    displayName: "Deploy Infrastructure"
    container: ${{if parameters.TerraformContainer}}
    dependsOn:
      - manualVerification
      - planInfrastructure
    condition: or(succeeded('manualVerification'), and(succeeded('planInfrastructure'), ne(dependencies.planInfrastructure.outputs['planInfrastructure.plan.needsVerification'], 'true')))
    environment: "${{ parameters.AzDOEnvironmentName }}"
    workspace:
      clean: all
    variables:
      - template: ${{variables['System.DefaultWorkingDirectory']}}${{ parameters.VariablesTemplateRelativePath }}@self
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: UKHOTemplates
              persistCredentials: true
              path: devops-pipelinetemplates

            - download: current
              artifact: "${{ parameters.TerraformArtifact }}"
              retryCountOnTaskFailure: '2'
              displayName: 'Download terraform artifact'

            - task: PowerShell@2
              displayName: "terraform apply"
              name: deployment
              inputs:
                targetType: filePath
                filePath: "$(Pipeline.Workspace)/devops-pipelinetemplates/gated-infrastructure-deploy/terraform-apply.ps1"
                arguments: >
                  -TFStateResourceGroupName ${{ parameters.TFStateResourceGroupName }}
                  -TFStateStorageAccountName ${{ parameters.TFStateStorageAccountName }}
                  -TFStateContainerName ${{ parameters.TFStateContainerName }}
                  -TFStateBlobName ${{ parameters.TFStateBlobName }}
                  -TerraformFilesDirectory "$(Pipeline.Workspace)/${{ parameters.TerraformArtifact }}${{ parameters.TerraformArtifactConfigRelativePath }}"
                  -Workspace ${{ lower(parameters.TerraformWorkspace) }}
                  -TerraformOutputVariables ${{ convertToJson(parameters.TerraformOutputVariables) }}
              env:
                ${{ each TerraformVariableMappings in parameters.TerraformVariableMappings }}:
                  ${{ TerraformVariableMappings.Key }}: ${{ TerraformVariableMappings.Value }}